=== thejos/JaxbMarshallingUnmarshalling/src/jaxbmarshallingunmarshalling/countries.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="countries">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" name="country"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="country">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string"/>
				<xs:element name="capital" type="xs:string"/>
				<xs:element name="description" type="xs:string"/>
			</xs:sequence>
			<xs:attribute name="countryCode" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== thejos/JaxbMarshallingUnmarshalling/src/jaxbmarshallingunmarshalling/countries.xml
<?xml version="1.0" encoding="UTF-8"?>
<countries xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="countries.xsd">
	<country countryCode="cz">
		<name>Czech Republic</name>
		<capital>Port Elbert</capital>
		<description>Debitis delectus aliquid minus officia veniam blanditiis veniam.</description>
	</country>
	<country countryCode="am">
		<name>Armenia</name>
		<capital>Lake Danstad</capital>
		<description>Velit error voluptate adipisci assumenda ipsam maiores.</description>
	</country>
	<country countryCode="pk">
		<name>Pakistan</name>
		<capital>Kaelaberg</capital>
		<description>Et dolor hic hic atque dolore velit veniam.</description>
	</country>
	<country countryCode="co">
		<name>Colombia</name>
		<capital>West Edgar</capital>
		<description>Itaque enim minima fugit.</description>
	</country>
</countries>
